name: Code Syntax Check
on:
  pull_request:
    branches:
      - master
      - group31-fall24
  push:
    branches:
      - master
      - group31-fall24
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: |
            cd Code/backend
            npm install
      - name: Lint
        run: |
            cd Code/backend
            npx eslint ./dao
